server {

    listen 80;

    server_name
        addigitallsolutions.in
        www.addigitallsolutions.in;

    root /usr/share/nginx/html;

    index index.html;

    location / {
        try_files $uri $uri.html $uri/ =404;
    }

    location ~* \.(css|js|png|jpg|jpeg|gif|svg|ico|woff2?|ttf|webp)$ {

        expires 30d;

        access_log off;

        add_header Cache-Control "public";
    }

}